package io.orvanta.forge;

import io.orvanta.core.data.Rec;
import io.orvanta.core.expr.Ops;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Turns one model into the source of one Java class. The generated classes extend the base
 * types in {@code io.orvanta.core.flow.Elements} and call only {@code Ops}, {@code Fn} and {@code Rec},
 * so they are readable and can be stepped through in any Java debugger.
 */
final class Generator {

    static final String PACKAGE = "orv.gen";
    static final Set<String> CODE_KINDS = Set.of("RuleSet", "Mapping", "DecisionTable", "Flow", "TestCase");
    static final Set<String> CONFIG_KINDS = Set.of("Channel", "Connector", "ReferenceTable", "DataSet", "Api", "MessageSpec", "Format", "Schedule", "TestCase");

    private static final String IDENT = "[A-Za-z_][A-Za-z0-9_]*";
    private static final String PATH = "[A-Za-z0-9_@#][A-Za-z0-9_]*(\\.[A-Za-z0-9_@#][A-Za-z0-9_]*)*";

    /** name to kind of every model in the build, for reference checks */
    private final Map<String, String> kinds;

    Generator(Map<String, String> kinds) {
        this.kinds = kinds;
    }

    static String className(ModelSource m) {
        return m.kind() + "_" + m.name().replaceAll("[^A-Za-z0-9]", "_");
    }

    String generate(ModelSource m) {
        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(PACKAGE).append(";\n\n")
                .append("import io.orvanta.core.data.Rec;\n")
                .append("import io.orvanta.core.expr.Fn;\n")
                .append("import io.orvanta.core.expr.Ops;\n")
                .append("import io.orvanta.core.flow.Elements;\n")
                .append("import io.orvanta.core.flow.FlowContext;\n")
                .append("import io.orvanta.core.flow.Violation;\n")
                .append("import java.util.ArrayList;\n")
                .append("import java.util.List;\n\n")
                .append("/** Generated by Orvanta Forge from ").append(m.kind()).append(' ').append(m.name()).append(". Do not edit. */\n");
        String base = switch (m.kind()) {
            case "RuleSet" -> "Elements.RuleSet";
            case "Mapping" -> "Elements.Mapping";
            case "DecisionTable" -> "Elements.DecisionTable";
            case "Flow" -> "Elements.Flow";
            case "TestCase" -> "Elements.Checks";
            default -> throw new ModelException("kind", "unknown kind '" + m.kind() + "'");
        };
        sb.append("public final class ").append(className(m)).append(" extends ").append(base).append(" {\n\n")
                .append("    public String name() {\n        return ").append(lit(m.name())).append(";\n    }\n\n");
        switch (m.kind()) {
            case "RuleSet" -> ruleSet(m, sb);
            case "Mapping" -> mapping(m, sb);
            case "DecisionTable" -> decisionTable(m, sb);
            case "Flow" -> flow(m, sb);
            default -> testCase(m, sb);
        }
        return sb.append("}\n").toString();
    }

    // ---- RuleSet ----

    private void ruleSet(ModelSource m, StringBuilder sb) {
        sb.append("    public List<Violation> check(Rec $s) {\n")
                .append("        List<Violation> $v = new ArrayList<>();\n");
        int n = 0;
        for (Object o : items(m.def(), "rules")) {
            Rec rule = asRec(o, "rules[" + n + "]");
            String id = required(rule, "id", "rules[" + n + "]");
            String where = "rule " + id;
            String code = rule.str("code") == null ? id : rule.str("code");
            String message = rule.str("message") == null ? id : rule.str("message");
            String severity = rule.str("severity") == null ? "error" : rule.str("severity");
            if (!severity.equals("error") && !severity.equals("warning")) {
                throw new ModelException(where, "severity must be error or warning");
            }
            String violation = "new Violation(" + lit(id) + ", " + lit(code) + ", ";
            sb.append("        try {\n");
            String indent = "            ";
            if (rule.get("when") != null) {
                sb.append(indent).append("if (Ops.truthy(").append(expr(rule, "when", where, Map.of())).append("))\n");
                indent += "    ";
            }
            sb.append(indent).append("if (!Ops.truthy(").append(expr(rule, "assert", where, Map.of())).append(")) {\n")
                    .append(indent).append("    $v.add(").append(violation).append(lit(message)).append(", ").append(lit(severity)).append("));\n")
                    .append(indent).append("}\n")
                    .append("        } catch (RuntimeException $e) {\n")
                    .append("            $v.add(").append(violation).append(lit(message + " (") + " + $e.getMessage() + \")\", ").append(lit(severity)).append("));\n")
                    .append("        }\n");
            n++;
        }
        sb.append("        return $v;\n    }\n");
    }

    // ---- Mapping ----

    private void mapping(ModelSource m, StringBuilder sb) {
        String target = m.def().str("target");
        if (target != null && !target.matches(PATH)) {
            throw new ModelException("target", "'" + target + "' is not a valid scope path");
        }
        sb.append("    public Rec apply(Rec $s) {\n")
                .append("        Rec $t0 = ").append(target == null ? "new Rec()" : "$s.rec(" + lit(target) + ")").append(";\n");
        Map<String, String> locals = new HashMap<>();
        locals.put("out", "((Object) $t0)");
        mappingRules(items(m.def(), "rules"), 0, locals, "        ", "rules", sb);
        sb.append("        return $t0;\n    }\n");
    }

    private void mappingRules(List<?> rules, int depth, Map<String, String> locals, String indent, String where, StringBuilder sb) {
        locals = new HashMap<>(locals);
        String target = "$t" + depth;
        int n = 0;
        for (Object o : rules) {
            String at = where + "[" + n++ + "]";
            Rec rule = asRec(o, at);
            String body = indent;
            boolean guarded = rule.get("when") != null && rule.get("forEach") == null;
            if (guarded) {
                sb.append(indent).append("if (Ops.truthy(").append(expr(rule, "when", at, locals)).append(")) {\n");
                body = indent + "    ";
            }
            if (rule.get("set") != null) {
                String path = rule.str("set");
                if (!path.matches(PATH)) {
                    throw new ModelException(at, "'" + path + "' is not a valid target path");
                }
                at = "set " + path;
                sb.append(body).append("try {\n")
                        .append(body).append("    Object $x = ").append(expr(rule, "value", at, locals)).append(";\n")
                        .append(body).append("    if (!Ops.blank($x)) {\n")
                        .append(body).append("        ").append(target).append(".set(").append(lit(path)).append(", $x);\n")
                        .append(body).append("    }\n")
                        .append(body).append("} catch (RuntimeException $e) {\n")
                        .append(body).append("    throw new IllegalStateException(").append(lit(at + ": ")).append(" + $e.getMessage(), $e);\n")
                        .append(body).append("}\n");
            } else if (rule.get("let") != null) {
                String name = identifier(rule.str("let"), at);
                if (guarded) {
                    throw new ModelException(at, "'let' cannot have a 'when'; use a conditional expression as its value");
                }
                if (locals.containsKey(name)) {
                    throw new ModelException(at, "variable '" + name + "' is already defined");
                }
                sb.append(body).append("Object v_").append(name).append(" = ").append(expr(rule, "value", "let " + name, locals)).append(";\n");
                locals.put(name, "v_" + name);
            } else if (rule.get("forEach") != null) {
                String name = identifier(required(rule, "as", at), at);
                if (locals.containsKey(name)) {
                    throw new ModelException(at, "variable '" + name + "' is already defined");
                }
                String append = rule.str("append");
                if (append != null && !append.matches(PATH)) {
                    throw new ModelException(at, "'" + append + "' is not a valid target path");
                }
                String source = expr(rule, "forEach", at, locals);
                Map<String, String> inner = new HashMap<>(locals);
                inner.put(name, "v_" + name);
                inner.put(name + "Index", "((Object) java.math.BigDecimal.valueOf(i_" + name + "))");
                String in = body + "    ";
                // own block: sibling loops may reuse the same variable name
                sb.append(body).append("{\n");
                sb.append(body).append("int i_").append(name).append(" = -1;\n")
                        .append(body).append("for (Object v_").append(name).append(" : Ops.list(").append(source).append(")) {\n")
                        .append(in).append("i_").append(name).append("++;\n");
                if (rule.get("when") != null) {
                    sb.append(in).append("if (!Ops.truthy(").append(expr(rule, "when", at, inner)).append(")) {\n")
                            .append(in).append("    continue;\n").append(in).append("}\n");
                }
                List<?> nested = items(rule, "rules");
                if (append == null) {
                    mappingRules(nested, depth, inner, in, at + ".rules", sb);
                } else {
                    String child = "$t" + (depth + 1);
                    sb.append(in).append("Rec ").append(child).append(" = new Rec();\n");
                    mappingRules(nested, depth + 1, inner, in, at + ".rules", sb);
                    sb.append(in).append("if (!").append(child).append(".isEmpty()) {\n")
                            .append(in).append("    ").append(target).append(".list(").append(lit(append)).append(").add(").append(child).append(");\n")
                            .append(in).append("}\n");
                }
                sb.append(body).append("}\n").append(body).append("}\n");
            } else if (rule.get("field") != null) {
                // SWIFT MT shorthand: appends {tag, value} to the field list of the current message
                String tag = rule.str("field");
                if (!tag.matches("[0-9]{2}[A-Z]?")) {
                    throw new ModelException(at, "'" + tag + "' is not an MT field tag such as 20, 32A or 59");
                }
                at = "field " + tag;
                sb.append(body).append("try {\n")
                        .append(body).append("    Object $x = ").append(expr(rule, "value", at, locals)).append(";\n")
                        .append(body).append("    if (!Ops.blank($x)) {\n")
                        .append(body).append("        ").append(target).append(".list(\"fields\").add(Rec.of(\"tag\", ").append(lit(tag)).append(", \"value\", Ops.str($x)));\n")
                        .append(body).append("    }\n")
                        .append(body).append("} catch (RuntimeException $e) {\n")
                        .append(body).append("    throw new IllegalStateException(").append(lit(at + ": ")).append(" + $e.getMessage(), $e);\n")
                        .append(body).append("}\n");
            } else if (rule.get("append") != null) {
                // one new record appended to a list, filled by the nested rules
                String append = rule.str("append");
                if (!append.matches(PATH)) {
                    throw new ModelException(at, "'" + append + "' is not a valid target path");
                }
                String child = "$t" + (depth + 1);
                sb.append(body).append("{\n")
                        .append(body).append("    Rec ").append(child).append(" = new Rec();\n");
                mappingRules(items(rule, "rules"), depth + 1, locals, body + "    ", at + ".rules", sb);
                sb.append(body).append("    if (!").append(child).append(".isEmpty()) {\n")
                        .append(body).append("        ").append(target).append(".list(").append(lit(append)).append(").add(").append(child).append(");\n")
                        .append(body).append("    }\n")
                        .append(body).append("}\n");
            } else {
                throw new ModelException(at, "a mapping rule needs one of: set, let, forEach, append, field");
            }
            if (guarded) {
                sb.append(indent).append("}\n");
            }
        }
    }

    // ---- DecisionTable ----

    private void decisionTable(ModelSource m, StringBuilder sb) {
        sb.append("    public String decide(Rec $s) {\n");
        int n = 0;
        for (Object o : items(m.def(), "rows")) {
            Rec row = asRec(o, "rows[" + n + "]");
            String id = required(row, "id", "rows[" + n + "]");
            String where = "row " + id;
            boolean conditional = row.get("when") != null;
            String indent = conditional ? "            " : "        ";
            if (conditional) {
                sb.append("        if (Ops.truthy(").append(expr(row, "when", where, Map.of())).append(")) {\n");
            } else {
                sb.append("        {\n");
                indent = "            ";
            }
            assignments(row, "set", where, indent, sb);
            sb.append(indent).append("return ").append(lit(id)).append(";\n        }\n");
            n++;
            if (!conditional) {
                if (n < items(m.def(), "rows").size()) {
                    throw new ModelException(where, "a row without 'when' matches everything and must be the last row");
                }
                sb.append("    }\n");
                return;
            }
        }
        sb.append("        return null;\n    }\n");
    }

    /** Emits scope assignments for a {path: expression} map. */
    private void assignments(Rec holder, String key, String where, String indent, StringBuilder sb) {
        Object set = holder.get(key);
        if (set == null) {
            return;
        }
        if (!(set instanceof Map<?, ?> map)) {
            throw new ModelException(where, "'" + key + "' must be a map of scope path to expression");
        }
        for (Map.Entry<?, ?> e : map.entrySet()) {
            String path = String.valueOf(e.getKey());
            if (!path.matches(PATH)) {
                throw new ModelException(where, "'" + path + "' is not a valid scope path");
            }
            sb.append(indent).append("$s.set(").append(lit(path)).append(", ")
                    .append(compile(String.valueOf(e.getValue()), where + ", " + path, Map.of())).append(");\n");
        }
    }

    // ---- Flow ----

    private void flow(ModelSource m, StringBuilder sb) {
        String complete = m.def().str("completeStatus");
        if (complete != null) {
            sb.append("    public String completeStatus() {\n        return ").append(lit(complete)).append(";\n    }\n\n");
        }
        StringBuilder methods = new StringBuilder();
        sb.append("    protected void execute(Rec $s, FlowContext ctx) throws Exception {\n");
        steps(items(m.def(), "steps"), "steps", "        ", sb, methods, new int[]{0});
        sb.append("    }\n").append(methods);
    }

    /** Emits the calls for a list of steps into the caller and one private method per step. */
    private void steps(List<?> steps, String where, String indent, StringBuilder calls, StringBuilder methods, int[] counter) {
        int n = 0;
        for (Object o : steps) {
            Rec step = asRec(o, where + "[" + n + "]");
            String id = required(step, "id", where + "[" + n + "]");
            String type = required(step, "type", "step " + id);
            String at = "step " + id;
            String method = "step" + counter[0]++ + "_" + id.replaceAll("[^A-Za-z0-9]", "_");
            calls.append(indent).append("if (!ctx.ended()) {\n")
                    .append(indent).append("    ctx.enter(").append(lit(id)).append(", ").append(lit(type)).append(");\n");
            if (step.get("when") != null) {
                calls.append(indent).append("    if (Ops.truthy(").append(expr(step, "when", at, Map.of())).append(")) {\n")
                        .append(indent).append("        ").append(method).append("($s, ctx);\n")
                        .append(indent).append("    } else {\n").append(indent).append("        ctx.skip();\n").append(indent).append("    }\n");
            } else {
                calls.append(indent).append("    ").append(method).append("($s, ctx);\n");
            }
            calls.append(indent).append("    ctx.leave();\n").append(indent).append("}\n");
            StringBuilder body = new StringBuilder();
            body.append("\n    private void ").append(method).append("(Rec $s, FlowContext ctx) throws Exception {\n");
            if (type.equals("forEach")) {
                // the current item is a scope variable, so nested steps and the elements they call can read it
                String as = identifier(required(step, "as", at), at);
                body.append("        int count = 0;\n")
                        .append("        for (Object item : Ops.list(").append(expr(step, "in", at, Map.of())).append(")) {\n")
                        .append("            if (ctx.ended()) {\n                break;\n            }\n")
                        .append("            $s.put(").append(lit(as)).append(", item);\n")
                        .append("            count++;\n");
                if (items(step, "steps").isEmpty()) {
                    throw new ModelException(at, "a forEach step needs nested 'steps'");
                }
                steps(items(step, "steps"), at + ".steps", "            ", body, methods, counter);
                body.append("        }\n        ctx.note(count + \" item(s)\");\n");
            } else if (type.equals("parallel")) {
                // every nested step is a branch: it runs on its own copy of the scope with its own context, all at once;
                // afterwards what each changed is written into the scope, and the first branch to end the flow decides
                List<?> branches = items(step, "steps");
                if (branches.size() < 2) {
                    throw new ModelException(at, "a parallel step needs at least two nested 'steps', one per branch");
                }
                body.append("        Rec $before = $s.copy();\n")
                        .append("        List<java.util.concurrent.Callable<Object[]>> $branches = new ArrayList<>();\n");
                for (int b = 0; b < branches.size(); b++) {
                    String branch = method + "_branch" + b;
                    body.append("        $branches.add(() -> {\n")
                            .append("            Rec $b = $before.copy();\n")
                            .append("            FlowContext $c = ctx.fork();\n")
                            .append("            ").append(branch).append("($b, $c);\n")
                            .append("            return new Object[] {$b, $c};\n")
                            .append("        });\n");
                    StringBuilder branchBody = new StringBuilder();
                    branchBody.append("\n    private void ").append(branch).append("(Rec $s, FlowContext ctx) throws Exception {\n");
                    steps(List.of(branches.get(b)), at + ".steps[" + b + "]", "        ", branchBody, methods, counter);
                    branchBody.append("    }\n");
                    methods.append(branchBody);
                }
                body.append("        for (Object[] $r : io.orvanta.core.flow.Parallel.run($branches)) {\n")
                        .append("            ctx.join((FlowContext) $r[1]);\n")
                        .append("            io.orvanta.core.flow.Parallel.merge($s, (Rec) $r[0], $before);\n")
                        .append("        }\n")
                        .append("        ctx.note(\"").append(branches.size()).append(" branches\");\n");
            } else {
                stepBody(step, type, at, body);
            }
            body.append("    }\n");
            methods.append(body);
            n++;
        }
    }

    private void stepBody(Rec step, String type, String where, StringBuilder sb) {
        String in = "        ";
        switch (type) {
            case "rules" -> {
                String ref = reference(step, "ref", "RuleSet", where);
                String on = option(step, "onViolation", "reject", where, "reject", "continue");
                sb.append(in).append("List<Violation> found = ctx.ruleSet(").append(lit(ref)).append(").check($s);\n")
                        .append(in).append("ctx.addViolations(found);\n")
                        .append(in).append("ctx.note(found.size() + \" violation(s)\");\n");
                if (on.equals("reject")) {
                    sb.append(in).append("Violation first = ctx.firstError(found);\n")
                            .append(in).append("if (first != null) {\n")
                            .append(in).append("    ctx.end(").append(lit(statusOf(step, "REJECTED"))).append(", first.code(), first.message());\n")
                            .append(in).append("}\n");
                }
            }
            case "map" -> {
                String ref = reference(step, "ref", "Mapping", where);
                String into = step.str("into");
                if (into == null) {
                    sb.append(in).append("ctx.mapping(").append(lit(ref)).append(").apply($s);\n");
                } else {
                    scopePath(into, where);
                    sb.append(in).append("$s.set(").append(lit(into)).append(", ctx.mapping(").append(lit(ref)).append(").apply($s));\n");
                }
            }
            case "set" -> {
                if (step.get("values") == null) {
                    throw new ModelException(where, "a set step needs 'values'");
                }
                assignments(step, "values", where, in, sb);
            }
            case "decide" -> {
                String ref = reference(step, "ref", "DecisionTable", where);
                String on = option(step, "onNoMatch", "reject", where, "reject", "continue");
                sb.append(in).append("String row = ctx.decision(").append(lit(ref)).append(").decide($s);\n")
                        .append(in).append("ctx.note(row == null ? \"no row matched\" : \"row \" + row);\n");
                if (on.equals("reject")) {
                    sb.append(in).append("if (row == null) {\n")
                            .append(in).append("    ctx.end(").append(lit(statusOf(step, "REJECTED"))).append(", ")
                            .append(lit(step.str("code") == null ? "NO_DECISION" : step.str("code"))).append(", ")
                            .append(lit(step.str("message") == null ? "no row of " + ref + " matched" : step.str("message"))).append(");\n")
                            .append(in).append("}\n");
                }
            }
            case "call" -> {
                String connector = reference(step, "connector", "Connector", where);
                String into = scopePath(required(step, "into", where), where);
                String on = option(step, "onError", "repair", where, "repair", "reject", "continue");
                if (Boolean.parseBoolean(String.valueOf(step.get("once")))) {
                    // the flow is run again after a hold, a late answer or a retry: an answer already obtained is kept
                    sb.append(in).append("Object earlier = $s.at(").append(lit(into)).append(");\n")
                            .append(in).append("if (!Ops.blank(earlier) && Ops.get(earlier, \"error\") == null) {\n")
                            .append(in).append("    ctx.note(\"earlier answer reused\");\n")
                            .append(in).append("    return;\n").append(in).append("}\n");
                }
                sb.append(in).append("Rec request = new Rec();\n");
                Object request = step.get("request");
                if (request != null && !(request instanceof Map<?, ?>)) {
                    throw new ModelException(where, "'request' must be a map of field to expression");
                }
                if (request instanceof Map<?, ?> map) {
                    for (Map.Entry<?, ?> e : map.entrySet()) {
                        sb.append(in).append("request.set(").append(lit(scopePath(String.valueOf(e.getKey()), where))).append(", ")
                                .append(compile(String.valueOf(e.getValue()), where + ", request " + e.getKey(), Map.of())).append(");\n");
                    }
                }
                sb.append(in).append("try {\n")
                        .append(in).append("    $s.set(").append(lit(into)).append(", ctx.connector(").append(lit(connector)).append(").call(request));\n")
                        .append(in).append("} catch (Exception $e) {\n")
                        .append(in).append("    String problem = ").append(lit("connector " + connector + " failed: ")).append(" + $e.getMessage();\n")
                        .append(in).append("    ctx.note(problem);\n");
                switch (on) {
                    // an outage is CONNECTOR_ERROR, which the engine tries again; a refusal by the system is CONNECTOR_REFUSED, which it does not
                    case "repair" -> sb.append(in).append("    ctx.end(\"REPAIR\", $e instanceof io.orvanta.core.flow.ConnectorRefusal ? \"CONNECTOR_REFUSED\" : \"CONNECTOR_ERROR\", problem);\n");
                    case "reject" -> sb.append(in).append("    ctx.end(").append(lit(statusOf(step, "REJECTED")))
                            .append(", $e instanceof io.orvanta.core.flow.ConnectorRefusal ? \"CONNECTOR_REFUSED\" : \"CONNECTOR_ERROR\", problem);\n");
                    default -> sb.append(in).append("    $s.set(").append(lit(into)).append(", Rec.of(\"error\", problem));\n");
                }
                sb.append(in).append("}\n");
            }
            case "find" -> {
                String dataset = reference(step, "dataset", "DataSet", where);
                String into = scopePath(required(step, "into", where), where);
                boolean first = Boolean.parseBoolean(String.valueOf(step.get("first")));
                Object conditions = step.get("where");
                if (conditions != null && !(conditions instanceof Map<?, ?>)) {
                    throw new ModelException(where, "'where' must be a map of field to expression");
                }
                sb.append(in).append("Rec where = new Rec();\n").append(in).append("boolean answerable = true;\n");
                if (conditions instanceof Map<?, ?> map) {
                    for (Map.Entry<?, ?> e : map.entrySet()) {
                        String field = scopePath(String.valueOf(e.getKey()), where);
                        if (e.getValue() instanceof Map<?, ?> operators) {
                            // a range, "not" or "one of": {gte: expression, lt: expression}; a condition without a value can match nothing
                            sb.append(in).append("{\n").append(in).append("    Rec $cond = new Rec();\n");
                            for (Map.Entry<?, ?> op : operators.entrySet()) {
                                String operator = String.valueOf(op.getKey());
                                if (!io.orvanta.core.data.Conditions.OPERATORS.contains(operator)) {
                                    throw new ModelException(where + ", where " + field, "'" + operator + "' is not a condition; use gt, gte, lt, lte, ne or in");
                                }
                                sb.append(in).append("    {\n")
                                        .append(in).append("        Object $w = Ops.unwrap(").append(compile(String.valueOf(op.getValue()), where + ", where " + field + " " + operator, Map.of())).append(");\n")
                                        .append(in).append("        if ($w == null) {\n").append(in).append("            answerable = false;\n")
                                        .append(in).append("        } else {\n").append(in).append("            $cond.put(").append(lit(operator)).append(", $w);\n")
                                        .append(in).append("        }\n").append(in).append("    }\n");
                            }
                            sb.append(in).append("    where.put(").append(lit(field)).append(", $cond);\n").append(in).append("}\n");
                            continue;
                        }
                        // a condition without a value can match nothing; dropping it would widen the search
                        sb.append(in).append("{\n")
                                .append(in).append("    Object $w = Ops.unwrap(").append(compile(String.valueOf(e.getValue()), where + ", where " + field, Map.of())).append(");\n")
                                .append(in).append("    if ($w == null) {\n").append(in).append("        answerable = false;\n")
                                .append(in).append("    } else {\n").append(in).append("        where.put(").append(lit(field)).append(", $w);\n")
                                .append(in).append("    }\n").append(in).append("}\n");
                    }
                }
                int limit = step.get("limit") == null ? (first ? 1 : 100) : Ops.num(step.get("limit")).intValue();
                int offset = step.get("offset") == null ? 0 : Ops.num(step.get("offset")).intValue();
                if (offset < 0) {
                    throw new ModelException(where, "'offset' is zero or more rows to skip");
                }
                sb.append(in).append("List<Rec> rows = answerable ? ctx.data().find(").append(lit(dataset)).append(", where, ")
                        .append(step.str("sort") == null ? "null" : lit(scopePath(step.str("sort"), where))).append(", ")
                        .append(Boolean.parseBoolean(String.valueOf(step.get("descending")))).append(", ").append(limit + offset).append(") : List.of();\n");
                if (offset > 0) {
                    // a page: the rows after the ones skipped
                    sb.append(in).append("rows = rows.size() > ").append(offset).append(" ? new ArrayList<>(rows.subList(").append(offset).append(", rows.size())) : new ArrayList<>();\n");
                }
                sb.append(in).append("ctx.note(rows.size() + \" row(s)\");\n");
                if (first) {
                    sb.append(in).append("$s.set(").append(lit(into)).append(", rows.isEmpty() ? null : rows.get(0));\n");
                } else {
                    sb.append(in).append("$s.set(").append(lit(into)).append(", new ArrayList<Object>(rows));\n");
                }
            }
            case "save" -> {
                String dataset = reference(step, "dataset", "DataSet", where);
                if (!(step.get("values") instanceof Map<?, ?> map)) {
                    throw new ModelException(where, "a save step needs 'values': a map of field to expression");
                }
                sb.append(in).append("Rec record = new Rec();\n");
                for (Map.Entry<?, ?> e : map.entrySet()) {
                    String field = scopePath(String.valueOf(e.getKey()), where);
                    sb.append(in).append("{\n")
                            .append(in).append("    Object $x = ").append(compile(String.valueOf(e.getValue()), where + ", values " + field, Map.of())).append(";\n")
                            .append(in).append("    if (!Ops.blank($x)) {\n").append(in).append("        record.set(").append(lit(field)).append(", $x);\n")
                            .append(in).append("    }\n").append(in).append("}\n");
                }
                boolean onlyIfAbsent = Boolean.parseBoolean(String.valueOf(step.get("onlyIfAbsent")));
                sb.append(in).append("boolean stored = ctx.data().save(").append(lit(dataset)).append(", record, ").append(onlyIfAbsent).append(");\n")
                        .append(in).append("ctx.note(stored ? \"stored\" : \"already present\");\n");
                if (step.str("into") != null) {
                    sb.append(in).append("$s.set(").append(lit(scopePath(step.str("into"), where))).append(", (Object) stored);\n");
                }
            }
            case "remove" -> {
                String dataset = reference(step, "dataset", "DataSet", where);
                sb.append(in).append("ctx.data().remove(").append(lit(dataset)).append(", Ops.unwrap(").append(expr(step, "key", where, Map.of())).append("));\n");
            }
            case "flow" -> {
                if (step.get("refExpr") != null) {
                    // the sub-flow is chosen while running, for example the checks of the rail the routing decided on
                    sb.append(in).append("String name = Ops.str(").append(expr(step, "refExpr", where, Map.of())).append(");\n")
                            .append(in).append("if (name == null) {\n")
                            .append(in).append("    throw new IllegalStateException(").append(lit(where + ": the expression named no flow")).append(");\n")
                            .append(in).append("}\n")
                            .append(in).append("ctx.flow(name).runWithin($s, ctx);\n")
                            .append(in).append("ctx.note(\"sub-flow \" + name);\n");
                } else {
                    String ref = reference(step, "ref", "Flow", where);
                    sb.append(in).append("ctx.flow(").append(lit(ref)).append(").runWithin($s, ctx);\n")
                            .append(in).append("ctx.note(\"sub-flow \" + ").append(lit(ref)).append(");\n");
                }
            }
            case "end" -> sb.append(in).append("ctx.end(").append(lit(required(step, "status", where))).append(", ")
                    .append(step.str("code") == null ? "null" : lit(step.str("code"))).append(", ")
                    .append(step.str("message") == null ? "null" : lit(step.str("message"))).append(");\n");
            case "wait" -> {
                // the flow stops here until an answer arrives (a callback fills a field) or a time has passed, and is run again
                // from the start; with 'for', a field already filled means there is nothing to wait for
                String code = required(step, "code", where);
                String waitFor = step.str("for") == null ? null : scopePath(step.str("for"), where);
                for (String key : new String[] {"retrySeconds", "timeoutSeconds"}) {
                    if (step.get(key) != null && (Ops.num(step.get(key)) == null || Ops.num(step.get(key)).signum() <= 0)) {
                        throw new ModelException(where, "'" + key + "' is a number of seconds above zero");
                    }
                }
                if (waitFor != null) {
                    sb.append(in).append("if (!Ops.blank($s.at(").append(lit(waitFor)).append("))) {\n")
                            .append(in).append("    ctx.note(\"").append(waitFor).append(" is there: nothing to wait for\");\n")
                            .append(in).append("    return;\n").append(in).append("}\n");
                }
                if (step.get("retrySeconds") != null) {
                    sb.append(in).append("$s.set(\"txn.wait.retrySeconds\", ").append(Ops.num(step.get("retrySeconds")).longValue()).append("L);\n");
                }
                if (step.get("timeoutSeconds") != null) {
                    sb.append(in).append("$s.set(\"txn.wait.timeoutSeconds\", ").append(Ops.num(step.get("timeoutSeconds")).longValue()).append("L);\n");
                }
                sb.append(in).append("ctx.end(\"WAIT\", ").append(lit(code)).append(", ")
                        .append(step.str("message") == null ? "null" : lit(step.str("message"))).append(");\n");
            }
            case "task" -> {
                // a human task: the payment is held for a person in a named operator queue, with instructions; the flow runs again
                // from the start when the person releases it (the hold code is then among txn.overrides) or ends it when rejected
                String code = required(step, "code", where);
                String queue = required(step, "queue", where);
                if (!queue.matches("[A-Za-z][A-Za-z0-9 _-]{0,39}")) {
                    throw new ModelException(where, "'queue' is a short name of letters, digits, spaces, dash or underscore");
                }
                sb.append(in).append("if (Ops.in(").append(lit(code)).append(", $s.at(\"txn.overrides\"))) {\n")
                        .append(in).append("    ctx.note(\"decided by a person already\");\n")
                        .append(in).append("    return;\n").append(in).append("}\n")
                        .append(in).append("$s.set(\"txn.hold.queue\", ").append(lit(queue)).append(");\n");
                if (step.get("instructions") != null) {
                    sb.append(in).append("$s.set(\"txn.hold.instructions\", Ops.str(").append(compile(String.valueOf(step.get("instructions")), where + ", instructions", Map.of())).append("));\n");
                }
                sb.append(in).append("ctx.end(\"HOLD\", ").append(lit(code)).append(", ")
                        .append(step.str("message") == null ? lit("Waiting for " + queue) : lit(step.str("message"))).append(");\n");
            }
            default -> throw new ModelException(where, "unknown step type '" + type + "' (rules, map, set, decide, call, find, save, remove, forEach, parallel, wait, task, flow, end)");
        }
    }

    private static String statusOf(Rec step, String fallback) {
        return step.str("status") == null ? fallback : step.str("status");
    }

    // ---- TestCase ----

    private void testCase(ModelSource m, StringBuilder sb) {
        String target = required(m.def(), "target", "target");
        if (!kinds.containsKey(target) || !CODE_KINDS.contains(kinds.get(target)) || "TestCase".equals(kinds.get(target))) {
            throw new ModelException("target", "'" + target + "' is not a RuleSet, Mapping, DecisionTable or Flow in this workspace");
        }
        sb.append("    public List<String> failed(Rec $s) {\n        List<String> $f = new ArrayList<>();\n");
        int n = 0;
        for (Object o : items(m.def(), "expect")) {
            String text = String.valueOf(o);
            String java = compile(text, "expect[" + n++ + "]", Map.of());
            sb.append("        try {\n            if (!Ops.truthy(").append(java).append(")) {\n")
                    .append("                $f.add(").append(lit(text)).append(");\n            }\n")
                    .append("        } catch (RuntimeException $e) {\n            $f.add(").append(lit(text + " -> ")).append(" + $e.getMessage());\n        }\n");
        }
        sb.append("        return $f;\n    }\n");
    }

    // ---- helpers ----

    private static String lit(String s) {
        return ExprCompiler.javaString(s);
    }

    private static String compile(String expression, String where, Map<String, String> locals) {
        try {
            return ExprCompiler.compile(expression, locals);
        } catch (ModelException e) {
            throw new ModelException(where, e.getMessage());
        }
    }

    private static String expr(Rec holder, String key, String where, Map<String, String> locals) {
        Object v = holder.get(key);
        if (v == null) {
            throw new ModelException(where, "'" + key + "' is required");
        }
        return compile(Ops.str(v), where + ", " + key, locals);
    }

    private static String required(Rec holder, String key, String where) {
        String v = holder.str(key);
        if (v == null || v.isBlank()) {
            throw new ModelException(where, "'" + key + "' is required");
        }
        return v;
    }

    private static String option(Rec holder, String key, String fallback, String where, String... allowed) {
        String v = holder.str(key) == null ? fallback : holder.str(key);
        if (!List.of(allowed).contains(v)) {
            throw new ModelException(where, "'" + key + "' must be one of " + List.of(allowed));
        }
        return v;
    }

    private String reference(Rec holder, String key, String kind, String where) {
        String ref = required(holder, key, where);
        String actual = kinds.get(ref);
        if (actual == null) {
            throw new ModelException(where, kind + " '" + ref + "' does not exist in this workspace");
        }
        if (!actual.equals(kind)) {
            throw new ModelException(where, "'" + ref + "' is a " + actual + " but a " + kind + " is needed");
        }
        return ref;
    }

    private static String scopePath(String path, String where) {
        if (!path.matches(PATH)) {
            throw new ModelException(where, "'" + path + "' is not a valid scope path");
        }
        return path;
    }

    private static String identifier(String name, String where) {
        if (name == null || !name.matches(IDENT)) {
            throw new ModelException(where, "'" + name + "' is not a valid variable name");
        }
        return name;
    }

    private static List<?> items(Rec holder, String key) {
        Object v = holder.get(key);
        if (v == null) {
            return List.of();
        }
        if (!(v instanceof List<?> l)) {
            throw new ModelException(key, "'" + key + "' must be a list");
        }
        return l;
    }

    private static Rec asRec(Object o, String where) {
        if (!(o instanceof Rec r)) {
            throw new ModelException(where, "expected a mapping of properties");
        }
        return r;
    }
}
