apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orvanta.fullname" . }}-config
  labels:
    {{- include "orvanta.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
  ORVANTA_SERVER_BEHINDTLSPROXY: "true"
  {{- end }}
