apiVersion: v1
kind: Service
metadata:
  name: {{ include "orvanta.fullname" . }}-console
  labels:
    {{- include "orvanta.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "orvanta.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
